---
- hosts: uat
  become: true
  tasks:
    - name: update cache
      apt:
        update_cache: yes
    - name: install pip
      apt:
        name: python3-pip
        state: present
    - name: install docker-py module
      pip:
        name: docker-py
        state: present
    - name: start the container
      docker_container:
         name: axe
         image: 2222s/axe:V-8
         state: started
         published_ports:
           - 0.0.0.0:83:8080
           - 0.0.0.0:84:8080
         
